server:
  port: 80
  tomcat:    uri-encoding: utf-8
#

spring:
  profiles:    active:    - localhost
  resources:    static-locations:    - classpath:/META-INF/resources/
    - classpath:/resources/
    - classpath:/static/
    - classpath:/public/
    - file:./fileupload/
  aop:
    proxy-target-class: true
  datasource:
    hikari:      minimum-idle: 5
      maximum-pool-size: 50
      auto-commit: true
      idle-timeout: 60000
      pool-name: DatebookHikariCP
      max-lifetime: 180000
      connection-timeout: 1800
      connection-test-query: SELECT 1
#    schema: 
#      - classpath:sql/healthy.sys_assess_adl_info_ddl.sql
#      - classpath:sql/healthy.sys_assess_asia_info_ddl.sql
#      - classpath:sql/healthy.sys_assess_ashworth_info_ddl.sql
#      - classpath:sql/healthy.sys_assess_brunnstrom_ddl.sql
#      - classpath:sql/healthy.sys_assess_fim_info_ddl.sql
#      - classpath:sql/healthy.sys_assess_info_ddl.sql
#      - classpath:sql/healthy.sys_assess_risk_info_ddl.sql
#      - classpath:sql/healthy.sys_healthy_base_info_ddl.sql
#      - classpath:sql/healthy.sys_use_assess_info_ddl.sql
#      - classpath:sql/healthy.sys_use_assess_suggestion_ddl.sql
#    data:
#      - classpath:sql/healthy.sys_assess_adl_info_config.sql
#      - classpath:sql/healthy.sys_assess_ashworth_info_config.sql
#      - classpath:sql/healthy.sys_assess_asia_info_config.sql
#      - classpath:sql/healthy.sys_assess_brunnstrom_config.sql
#      - classpath:sql/healthy.sys_assess_fim_info_config.sql
#      - classpath:sql/healthy.sys_assess_info_config.sql
#      - classpath:sql/healthy.sys_assess_risk_info_config.sql
#      - classpath:sql/healthy.sys_healthy_base_info_config.sql
#      - classpath:sql/healthy.sys_use_assess_info_config.sql
#      - classpath:sql/healthy.sys_use_assess_suggestion_config.sql

  servlet:
    multipart:
      max-file-size: 100000000
      max-request-size: 100000000
  jackson:
    date-format: yyyy-MM-dd HH:mm:ss
    joda-date-time-format: yyyy-MM-dd HH:mm:ss
    time-zone: GMT+8
  jpa:  
    database: MYSQL
#    open-in-view: false
    hibernate:
      ddl-auto: update
      naming-strategy: org.hibernate.cfg.ImprovedNamingStrategy
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL5Dialect
        show_sql: true
        format_sql: true
        use_sql_comments: true
    show-sql: true
  thymeleaf:
    servlet:      content-type: text/html
    encoding: UTF-8
    cache: false
    mode: HTML
  main:
    banner-mode: console
    web-application-type: servlet
    allow-bean-definition-overriding: true
    
jwt:
  tokenHeader: Authorization
  tokenPrefix: Bearer
  secret: lanjwt
  expiration: 3600
  rememberExpiration: 604800
  
  
logging:
  level:
    root: INFO
    org.hibernate: INFO
#    org.hibernate.type.descriptor.sql.BasicBinder: trace
#    org.hibernate.type.descriptor.sql.BasicExtractor: trace
    org.danyuan: DEBUG
